version: "3"

volumes:
  django-tutorial-pg-data:

services:
  db:
    image: postgres:14.5-bullseye
    container_name: postgres
    expose:
      - 5432/tcp
    volumes:
      - django-tutorial-pg-data:/var/lib/postgresql/data:rw
    env_file:
      - db.env
    restart: always
    

  app01:
    image: app01:latest
    build: ../app01/
    container_name: app01
    ports:
      - 8001:8000/tcp
    volumes:
      - ../app01/:/usr/src/app
    user: "${UID}:${GID}"
    env_file:
      - app01.env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
